# httpbin-mapping.yaml
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: httpbin-mapping
  namespace: ambassador
spec:
  hostname: "*"
  prefix: /httpbin/
  service: httpbin.ambassador.svc.cluster.local:8888
  labels:
    ambassador: # domain
      - header_request_label:
          - request_headers:
              key: user_id
              header_name: "x-user-id"
      - header_request_label_client_type:
          - request_headers:
              key: client_type
              header_name: "x-client-type"
